### ISSUE TITLE
[Solved] My images are grayed out.

### ISSUE THREAD

**Issue by adrian1906** [clavicule/BBTag#1]
My expectation is that when I navigate to the folder containing the images, I would then click on an image and it would appear in the display window.  All my images are grayed out and nothing appears when I click on them.

**Comment by clavicule** [comment]
Hello Adrian,

the most-left panel is indeed a folder navigation area which allows you to find/select the images on which to work on.
![selecting_images](https://cloud.githubusercontent.com/assets/4286942/22333368/7b8a0bdc-e39b-11e6-9b7a-7cf28776f6b5.png)

At this point, images won't be displayed in the preview unless they are transferred to the working/labeling area using the 'right' arrow in between the 2 panels. Once they are in the labeling panel, each time you select a different image, the viewer will update.
![working_area](https://cloud.githubusercontent.com/assets/4286942/22333163/20b42c16-e39a-11e6-9f91-f20fd00701c1.png)

Note that you can select multiple images at the same time as well as folder (which will grab all the images in that folder).

You also mentioned the files were greyed out, there could be 2 reasons for that:
- the files are not supported image type
- you don't have read permissions on them (unlikely I assume).

So I will go with the first possibility: **what are the file extensions of the images?**
The default supported types are listed [here](https://doc-snapshots.qt.io/qt5-5.7/qimagereader.html#supportedImageFormats).

Then based on your system libraries, the format listed [here](https://doc-snapshots.qt.io/qt5-5.7/qtimageformats-index.html) may be supported too. For instance, if you have .TIFF images support, you should be able to select the images.

![tiff_file](https://cloud.githubusercontent.com/assets/4286942/22333261/c9e646f2-e39a-11e6-9a47-feb4dc25d78f.png)

Let me know.
cheers

**Comment by adrian1906** [comment]
I chose a folder with a mix of jpegs (.jpg extension) and .png files. The .png files transferred when I clicked the right arrow. The .jpg files did not.  I changed the extension on a few files to .jpeg and that did not work.  I also changed the permissions an all the files to 776 and restarted your program. It did not work.

The jpeg files are not corrupt as I can open them in other programs.  I notice that you only have .png files in the example you provided.

**Comment by clavicule** [comment]
this is indeed strange, especially because jpg/jpeg format is very standard. I grabbed a jpg/jpeg on the web randomly and didn't get any issue:
![palm_tree_example](https://cloud.githubusercontent.com/assets/4286942/22335508/a80aa758-e3a4-11e6-9edc-7a0b8571eb01.png)

I am sorry about this issue, let's see if we can sort it out:
- would you mind grabbing a random jpg/jpeg on the web (e.g. google image) and trying if it works?
- which platform are you using? I would like to hope it is MacOS which may explain the problem: packaging binaries on mac with Qt dependencies is quite tricky and I remember encountering problems. It is therefore possible I missed a plugin in the dmg archive (I am not a mac developer but I was trying to provide the package for all 3 major platforms). I will try to get my hand on a mac and test jpg/jpeg on it in the meantime.

**Comment by clavicule** [comment]
Let me amend my last comment: you are on Linux :)

From my developer environment, I don't have any problem. Downloading the packages, jpg/jpeg are indeed greyed out:
![greyed_out](https://cloud.githubusercontent.com/assets/4286942/22336013/7594ae34-e3a6-11e6-9d94-c812b2e68769.png)

So I actually missed something when packaging on Linux... I am very sorry about that, let me see if I can find the culprit quickly.

Alternatively, if you have a Qt-devenv ready, you should be able to make it work by building from source (not sure if this is an alternative you are interested in)

**Comment by clavicule** [comment]
Alright, I updated the package for Ubuntu in the [v1.1 release](https://github.com/clavicule/BBTag/releases/tag/1.1) page, or use the [direct link](https://github.com/clavicule/BBTag/releases/download/1.1/BBTag_ubuntu15.tar.gz) to download it.

The package was indeed missing the `imageformats` plugin. Once you extract the archive, you should see a `plugins\imageformats` folder and `BBTag.sh` should have an extra line:
```
export QT_PLUGIN_PATH=$dirname/plugins
```

Apologies for the inconvenience and thank you a lot for reporting the issue.
Please let me know if you confirm it solved the problem on your end.
thank you

**Comment by adrian1906** [comment]
You are correct. I'm using Ubuntu 16.04.
I downloaded the updated tar.gz file and it works like a charm.

Thanks for creating this great tool!
Adrian H.

**Comment by clavicule** [comment]
Thanks for double-checking on your side, again sorry for the problem, I'm glad you reported it, I clearly missed it when testing the package on locally.
I hope you like the tool and it will be useful. I haven't touched it in a while but feel free to make any suggestion or report any other problem.

cheers
