### ISSUE TITLE
Suggestion: Auto fit images

### ISSUE THREAD

**Issue by adrian1906** [clavicule/BBTag#2]
One suggestion would be to have a setting to auto scale to the width. This will make tagging a mix of horizontal and vertical images easier.

**Comment by clavicule** [comment]
Sounds good, I'll implement and commit it asap, it shouldn't be difficult

**Comment by clavicule** [comment]
Adrian,
the feature should be available after you update your local copy of BBTag and rebuild. 
Each time an image is loaded into the viewing area, it will be auto-scaled to its width.

**Comment by adrian1906** [comment]
Thanks again for the modification. I did a rebuild and now it looks like the menu bar/open/save buttons are missing.

![capture](https://cloud.githubusercontent.com/assets/18215812/22614971/e498cfd2-ea58-11e6-960e-b94c8238a4fe.JPG)
