### ISSUE TITLE
Incorrect keyboard mapping when using TightVNC

### ISSUE THREAD

**Issue by adrian1906** [clavicule/BBTag#3]
I'm having an issue when using BBTa via VNC.  My keys are not being mapped properly. I get the following error:

Qt: XKEYBOARD extension not present on the X server

I found a solution at https://bugreporsts.qt.io/browse/GTBUG-44938

set export XKB_DEFAULT_RULES=base

I'm unsure how to do this.  I looked through the source files and did not see and strings containing "XKB_DEFAULT".  

This site gives a little more information and claims it has to do with QT5. Unfortunately, no solution is provided:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814959

I'm able to tag without any problem. My workaround is to have a garbled label and a garbled filename and then just fix them via the shell.

**Comment by adrian1906** [comment]
I changed from TightVNC to VNC4Server and the problem was fixed.

**Comment by clavicule** [comment]
Thanks for finding out the problem and one solution. I have never tried any Qt app over VNC, I'm assuming this would happen with any Qt app?
